const international_phone_number = [
  { value: "+297", label: "ABW" },
  { value: "+93", label: "AFG" },
  { value: "+244", label: "AGO" },
  { value: "+1 264", label: "AIA" },
  { value: "+358", label: "ALA" },
  { value: "+355", label: "ALB" },
  { value: "+376", label: "AND" },
  { value: "+971", label: "ARE" },
  { value: "+54", label: "ARG" },
  { value: "+374", label: "ARM" },
  { value: "+1 684", label: "ASM" },
  { value: "+672", label: "ATA" },
  { value: "+262", label: "ATF" },
  { value: "+1 268", label: "ATG" },
  { value: "+61", label: "AUS" },
  { value: "+43", label: "AUT" },
  { value: "+994", label: "AZE" },
  { value: "+257", label: "BDI" },
  { value: "+32", label: "BEL" },
  { value: "+229", label: "BEN" },
  { value: "+599", label: "BES" },
  { value: "+226", label: "BFA" },
  { value: "+880", label: "BGD" },
  { value: "+359", label: "BGR" },
  { value: "+973", label: "BHR" },
  { value: "+1 242", label: "BHS" },
  { value: "+387", label: "BIH" },
  { value: "+590", label: "BLM" },
  { value: "+375", label: "BLR" },
  { value: "+501", label: "BLZ" },
  { value: "+1 441", label: "BMU" },
  { value: "+591", label: "BOL" },
  { value: "+55", label: "BRA" },
  { value: "+1 246", label: "BRB" },
  { value: "+673", label: "BRN" },
  { value: "+975", label: "BTN" },
  { value: "+47", label: "BVT" },
  { value: "+267", label: "BWA" },
  { value: "+236", label: "CAF" },
  { value: "+1", label: "CAN" },
  { value: "+61", label: "CCK" },
  { value: "+41", label: "CHE" },
  { value: "+56", label: "CHL" },
  { value: "+86", label: "CHN" },
  { value: "+225", label: "CIV" },
  { value: "+237", label: "CMR" },
  { value: "+243", label: "COD" },
  { value: "+242", label: "COG" },
  { value: "+682", label: "COK" },
  { value: "+57", label: "COL" },
  { value: "+269", label: "COM" },
  { value: "+238", label: "CPV" },
  { value: "+506", label: "CRI" },
  { value: "+53", label: "CUB" },
  { value: "+599", label: "CUW" },
  { value: "+61", label: "CXR" },
  { value: "+1 345", label: "CYM" },
  { value: "+357", label: "CYP" },
  { value: "+420", label: "CZE" },
  { value: "+49", label: "DEU" },
  { value: "+253", label: "DJI" },
  { value: "+1 767", label: "DMA" },
  { value: "+45", label: "DNK" },
  { value: "+213", label: "DZA" },
  { value: "+593", label: "ECU" },
  { value: "+20", label: "EGY" },
  { value: "+291", label: "ERI" },
  { value: "+212", label: "ESH" },
  { value: "+34", label: "ESP" },
  { value: "+372", label: "EST" },
  { value: "+251", label: "ETH" },
  { value: "+358", label: "FIN" },
  { value: "+679", label: "FJI" },
  { value: "+500", label: "FLK" },
  { value: "+33", label: "FRA" },
  { value: "+298", label: "FRO" },
  { value: "+691", label: "FSM" },
  { value: "+241", label: "GAB" },
  { value: "+44", label: "GBR" },
  { value: "+995", label: "GEO" },
  { value: "+44", label: "GGY" },
  { value: "+233", label: "GHA" },
  { value: "+350", label: "GIB" },
  { value: "+224", label: "GIN" },
  { value: "+590", label: "GLP" },
  { value: "+220", label: "GMB" },
  { value: "+245", label: "GNB" },
  { value: "+240", label: "GNQ" },
  { value: "+30", label: "GRC" },
  { value: "+1 473", label: "GRD" },
  { value: "+299", label: "GRL" },
  { value: "+502", label: "GTM" },
  { value: "+594", label: "GUF" },
  { value: "+1 671", label: "GUM" },
  { value: "+592", label: "GUY" },
  { value: "+852", label: "HKG" },
  { value: "+672", label: "HMD" },
  { value: "+504", label: "HND" },
  { value: "+385", label: "HRV" },
  { value: "+509", label: "HTI" },
  { value: "+36", label: "HUN" },
  { value: "+62", label: "IDN" },
  { value: "+44", label: "IMN" },
  { value: "+91", label: "IND" },
  { value: "+246", label: "IOT" },
  { value: "+353", label: "IRL" },
  { value: "+98", label: "IRN" },
  { value: "+964", label: "IRQ" },
  { value: "+354", label: "ISL" },
  { value: "+972", label: "ISR" },
  { value: "+39", label: "ITA" },
  { value: "+1 876", label: "JAM" },
  { value: "+44", label: "JEY" },
  { value: "+962", label: "JOR" },
  { value: "+81", label: "JPN" },
  { value: "+7", label: "KAZ" },
  { value: "+254", label: "KEN" },
  { value: "+996", label: "KGZ" },
  { value: "+855", label: "KHM" },
  { value: "+686", label: "KIR" },
  { value: "+1 869", label: "KNA" },
  { value: "+82", label: "KOR" },
  { value: "+965", label: "KWT" },
  { value: "+856", label: "LAO" },
  { value: "+961", label: "LBN" },
  { value: "+231", label: "LBR" },
  { value: "+218", label: "LBY" },
  { value: "+1 758", label: "LCA" },
  { value: "+423", label: "LIE" },
  { value: "+94", label: "LKA" },
  { value: "+266", label: "LSO" },
  { value: "+370", label: "LTU" },
  { value: "+352", label: "LUX" },
  { value: "+371", label: "LVA" },
  { value: "+853", label: "MAC" },
  { value: "+590", label: "MAF" },
  { value: "+212", label: "MAR" },
  { value: "+377", label: "MCO" },
  { value: "+373", label: "MDA" },
  { value: "+261", label: "MDG" },
  { value: "+960", label: "MDV" },
  { value: "+52", label: "MEX" },
  { value: "+692", label: "MHL" },
  { value: "+389", label: "MKD" },
  { value: "+223", label: "MLI" },
  { value: "+356", label: "MLT" },
  { value: "+95", label: "MMR" },
  { value: "+382", label: "MNE" },
  { value: "+976", label: "MNG" },
  { value: "+1 670", label: "MNP" },
  { value: "+258", label: "MOZ" },
  { value: "+222", label: "MRT" },
  { value: "+1 664", label: "MSR" },
  { value: "+596", label: "MTQ" },
  { value: "+230", label: "MUS" },
  { value: "+265", label: "MWI" },
  { value: "+60", label: "MYS" },
  { value: "+262", label: "MYT" },
  { value: "+264", label: "NAM" },
  { value: "+687", label: "NCL" },
  { value: "+227", label: "NER" },
  { value: "+672", label: "NFK" },
  { value: "+234", label: "NGA" },
  { value: "+505", label: "NIC" },
  { value: "+683", label: "NIU" },
  { value: "+31", label: "NLD" },
  { value: "+47", label: "NOR" },
  { value: "+977", label: "NPL" },
  { value: "+674", label: "NRU" },
  { value: "+64", label: "NZL" },
  { value: "+968", label: "OMN" },
  { value: "+92", label: "PAK" },
  { value: "+507", label: "PAN" },
  { value: "+870", label: "PCN" },
  { value: "+51", label: "PER" },
  { value: "+63", label: "PHL" },
  { value: "+680", label: "PLW" },
  { value: "+675", label: "PNG" },
  { value: "+48", label: "POL" },
  { value: "+1", label: "PRI" },
  { value: "+850", label: "PRK" },
  { value: "+351", label: "PRT" },
  { value: "+595", label: "PRY" },
  { value: "+970", label: "PSE" },
  { value: "+689", label: "PYF" },
  { value: "+974", label: "QAT" },
  { value: "+262", label: "REU" },
  { value: "+40", label: "ROU" },
  { value: "+7", label: "RUS" },
  { value: "+250", label: "RWA" },
  { value: "+966", label: "SAU" },
  { value: "+249", label: "SDN" },
  { value: "+221", label: "SEN" },
  { value: "+65", label: "SGP" },
  { value: "+500", label: "SGS" },
  { value: "+290", label: "SHN" },
  { value: "+47", label: "SJM" },
  { value: "+677", label: "SLB" },
  { value: "+232", label: "SLE" },
  { value: "+503", label: "SLV" },
  { value: "+378", label: "SMR" },
  { value: "+252", label: "SOM" },
  { value: "+508", label: "SPM" },
  { value: "+381", label: "SRB" },
  { value: "+211", label: "SSD" },
  { value: "+239", label: "STP" },
  { value: "+597", label: "SUR" },
  { value: "+421", label: "SVK" },
  { value: "+386", label: "SVN" },
  { value: "+46", label: "SWE" },
  { value: "+268", label: "SWZ" },
  { value: "+1 721", label: "SXM" },
  { value: "+248", label: "SYC" },
  { value: "+963", label: "SYR" },
  { value: "+1 649", label: "TCA" },
  { value: "+235", label: "TCD" },
  { value: "+228", label: "TGO" },
  { value: "+66", label: "THA" },
  { value: "+992", label: "TJK" },
  { value: "+690", label: "TKL" },
  { value: "+993", label: "TKM" },
  { value: "+670", label: "TLS" },
  { value: "+676", label: "TON" },
  { value: "+1 868", label: "TTO" },
  { value: "+216", label: "TUN" },
  { value: "+90", label: "TUR" },
  { value: "+688", label: "TUV" },
  { value: "+886", label: "TWN" },
  { value: "+255", label: "TZA" },
  { value: "+256", label: "UGA" },
  { value: "+380", label: "UKR" },
  { value: "+598", label: "URY" },
  { value: "+1", label: "USA" },
  { value: "+998", label: "UZB" },
  { value: "+1 784", label: "VCT" },
  { value: "+58", label: "VEN" },
  { value: "+1 284", label: "VGB" },
  { value: "+1 340", label: "VIR" },
  { value: "+84", label: "VNM" },
  { value: "+678", label: "VUT" },
  { value: "+681", label: "WLF" },
  { value: "+685", label: "WSM" },
  { value: "+967", label: "YEM" },
  { value: "+27", label: "ZAF" },
  { value: "+260", label: "ZMB" },
  { value: "+263", label: "ZWE" },
];

export default international_phone_number;
